### ISSUE TITLE
Server crashing when in the end

### ISSUE THREAD

**Issue by fermanek** [YeoXuHang/Geode-Plus#19]
I have a Minecraft server running Better Mc (1.19.2) which includes Geode +. After leaving the main End island and travelling to other end biomes server crashes leaving the message in the logs: net.yeoxuhang.geode.common.world.feature.WrappistCrystalSpikeFeature.placeSpike(WrappistCrystalSpikeFeature.java:98)

**Comment by YeoXuHang** [comment]
What Geode+ version are you using

**Comment by fermanek** [comment]
1.1.5
