### ISSUE TITLE
Geode crashes the game on startup [1.1.3] [1.19.2] [Forge 42.2.0] 

### ISSUE THREAD

**Issue by Mikeliro** [YeoXuHang/Geode-Plus#26]
The latest update is crashing the game on startup

Seems to be something with Infernal Geode [Line 35]
And Ars Nouveau [Line 97]
[crash-2022-12-12_13.35.08-client.txt](https://github.com/YeoXuHang/Geode-Plus/files/10210493/crash-2022-12-12_13.35.08-client.txt)

**Comment by AlfaM0de** [comment]
same

**Comment by YeoXuHang** [comment]
wait for infernal geode update
