### ISSUE TITLE
Incorrect calls to "serverLevel.random.nextInt" in several files.

### ISSUE THREAD

**Issue by Zamblom** [YeoXuHang/Geode-Plus#29]
Several files call "serverLevel.random.nextInt" with a parameter of 0. This throws an exception because the number must be a positive integer.

A brief overview spotted it in these two files, but it may appear in more:
- Geode-Plus/blob/master/common/src/main/java/net/yeoxuhang/geodeplus/common/block/EchoCrystalBlock.java:72
- Geode-Plus/blob/master/common/src/main/java/net/yeoxuhang/geodeplus/common/block/QuartzCrystalBlock.java:72

**Comment by YeoXuHang** [comment]
Fixed, will update after 23rd. due to exam

**Comment by Zamblom** [comment]
Cool, good to hear.
