### ISSUE TITLE
Nether Gold Nugget But texture problem

### ISSUE THREAD

**Issue by Nezila** [YeoXuHang/Geode-Plus#33]
Large Nether Gold Nugget Bud and Medium Nether Gold Nugget Bud have same texturas 
![Problemas](https://user-images.githubusercontent.com/106759862/219825680-c8b27591-6f85-4e41-9214-405bfb753f0d.png)
Yep, in the picture different blocks

**Comment by YeoXuHang** [comment]
Will fix in next update
