### ISSUE TITLE
How much lag do these Geodes cause?

### ISSUE THREAD

**Issue by allanonmage** [YeoXuHang/Geode-Plus#44]
I'm trying to chase down sudden random lag on my server, and looking around in Spectator mode, I see many geodes in the spawn chunks.  The server has been running for several months with this mod, so I'm kind of grasping at straws about what might be causing the lag, but I think the crystals getting ticked by the game might be a source, but several months in, idk if that's relevent or not.

Do your geodes cause much lag?  Do the crystals stop being ticked after they are full grown?

**Comment by YeoXuHang** [comment]
Crystals dont continue tick after fully grown
