### ISSUE TITLE
Disable cluster blocks?

### ISSUE THREAD

**Issue by douglasg14b** [YeoXuHang/Geode-Plus#46]
Blocks like the nether glowstone cluster block dominate the nether and little actual glowstone can be found (or is rather just really hard to find now). This block also has no uses, so it's can't be crafted/converted into glowstone either :/

The same goes for nether quartz crystal blocks.

How can these two things be disabled? Not the geodes, just the cluster blocks.

![image](https://github.com/YeoXuHang/Geode-Plus/assets/1400380/deec78b0-1c24-4a4a-8b66-fab1253751af)

**Comment by YeoXuHang** [comment]
This should be fixed now
