### ISSUE TITLE
this is supposed to happen?

### ISSUE THREAD

**Issue by peow** [YeoXuHang/Geode-Plus#53]
It appears that the new Geodes are capable of destroying Vanilla Minecraft structures, such as Stronghold
Maybe they can even destroy the portal to The End.
![huge_2023-09-27_14 44 08](https://github.com/YeoXuHang/Geode-Plus/assets/105888751/4b9304bc-2aa9-42f5-b5db-97434e0d1698)
![huge_2023-09-27_14 44 13](https://github.com/YeoXuHang/Geode-Plus/assets/105888751/7d0aa79e-7722-4542-8a0b-c24b2279e824)
![huge_2023-09-27_14 45 22](https://github.com/YeoXuHang/Geode-Plus/assets/105888751/314e067d-1be5-46ee-9ec6-792773e61f97)
![huge_2023-09-27_14 45 26](https://github.com/YeoXuHang/Geode-Plus/assets/105888751/402a7b60-76a7-46e7-9e3d-ce59cae4d4fc)

**Comment by YeoXuHang** [comment]
this shouldnt happen, will fix it

**Comment by YeoXuHang** [comment]
Yes you allow to silk touch the budding blocks

**Comment by YeoXuHang** [comment]
Yeah, I'll add custom config for it soon
