### ISSUE TITLE
[1.18.2 Forge] Nether Quartz geodes spawning in the overworld

### ISSUE THREAD

**Issue by vizthex123** [YeoXuHang/Geode-Plus#54]
Not sure why this is happening, but it is a bit annoying.

Log:
[latest.log](https://github.com/YeoXuHang/Geode-Plus/files/12744012/latest.log)

![image](https://github.com/YeoXuHang/Geode-Plus/assets/31721920/eb8bc7fc-647f-40af-a915-f359e6660f77)

**Comment by YeoXuHang** [comment]
We are no longer support 1.18.2 sorry

**Comment by vizthex123** [comment]
bruh.
