### ISSUE TITLE
The Wrappist Pedestal model is somehow "missing" and it's crashing my game.

### ISSUE THREAD

**Issue by MarcusTheAlbinoWolf** [YeoXuHang/Geode-Plus#55]
![Screenshot 2023-09-27 202644](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/852b4d4a-593c-4bfd-9994-8e185badca3b)

**Comment by YeoXuHang** [comment]
Mod list

**Comment by MarcusTheAlbinoWolf** [comment]
???

**Comment by MarcusTheAlbinoWolf** [comment]
> Mod list

Can you elaborate?

**Comment by YeoXuHang** [comment]
I need to see what you have installed, geode plus doesn't compatible with Patchouli for some reason

**Comment by MarcusTheAlbinoWolf** [comment]
> I need to see what you have installed, geode plus doesn't compatible with Patchouli for some reason

![Screenshot 2023-09-27 210009](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/7c93e93f-737d-4f2a-a103-f51e9073ffa9)
![Screenshot 2023-09-27 210039](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/a03f7aae-acc9-423d-919e-0327f44bd542)
![Screenshot 2023-09-27 210106](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/0e7b09b1-0741-4091-976f-d73baeb87855)
![Screenshot 2023-09-27 210138](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/aa63a0f2-412a-4603-8dd0-830153ae5a2b)
![Screenshot 2023-09-27 210204](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/9b331edc-1141-45cc-afdb-4af01378c349)
![Screenshot 2023-09-27 210230](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/6f66fd27-0826-4832-9161-8e4488058d42)
![Screenshot 2023-09-27 210248](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/44da24f0-475c-4a1e-a56d-2956df650017)
![Screenshot 2023-09-27 210304](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/189fa0d9-ece8-42af-8b16-f85fb069ccaf)
![Screenshot 2023-09-27 210340](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/a2a162c5-453e-491a-bb3a-0e7e4f2d6750)
![Screenshot 2023-09-27 210404](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/bbcea236-5a68-4169-b958-b96236feaf79)
![Screenshot 2023-09-27 210418](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/99d3fe7b-b8d1-468c-a2ba-dd60e72540af)
![Screenshot 2023-09-27 210429](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/6b5e350e-9138-4817-802e-cc3a3c845aa6)
![Screenshot 2023-09-27 210521](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/933e1255-05a2-4b69-8687-c1ba53397529)
![Screenshot 2023-09-27 210535](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/2b9248ad-58c6-4987-b961-927d4dccf66e)
![Screenshot 2023-09-27 210547](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/353b562c-737a-496e-8e5c-34547e4460b4)
![Screenshot 2023-09-27 210609](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/8f011186-a0ca-4176-b57c-b2f0f593caa4)
![Screenshot 2023-09-27 210636](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/63834513-7732-41a5-89c3-ec06c916c1cd)
![Screenshot 2023-09-27 210715](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/739e2347-a4fa-4aa5-8522-0a7636879e3b)
![Screenshot 2023-09-27 210739](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/e97e8612-edf1-4e7f-b56a-7c7d55d642de)
![Screenshot 2023-09-27 210748](https://github.com/YeoXuHang/Geode-Plus/assets/146309235/b48a9970-a91b-4897-9cc1-21ff88ecf723)

**Comment by YeoXuHang** [comment]
Ok, I'll check out soon, busy those days
