### ISSUE TITLE
Override of the vanilla recipe for gold nuggets.

### ISSUE THREAD

**Issue by devilunaworkshop** [YeoXuHang/Geode-Plus#58]
The mod overrides vanilla ingot_gold -> nugget_gold recipe and there is no config to disable that behaviour.

**Comment by EmmaKitten01** [comment]
Can confirm it also overrides the recipes for Lapis, Polymorph does not help here either

**Comment by Angelyques** [comment]
Can also confirm Diamond blocks can't be uncrafted either. Iron seems to the the only unaffected vanilla ore.

**Comment by ArghticFox** [comment]
Same issue with all gem blocks. Recipe for Block to Gem has been removed. Could not find crafting recipe in JEI.

**Comment by cjh15hub** [comment]
Please at least provide an option.
