### ISSUE TITLE
Crash on Fabric 1.20.1

### ISSUE THREAD

**Issue by rilakuma123** [YeoXuHang/Geode-Plus#59]
Minecraft 1.20.1
Fabric Loader 0.14.23
Fabric API 0.90.0
Geode+ 1.2.1

**Crash report**
[crash-2023-10-16_20.47.06-client.txt](https://github.com/YeoXuHang/Geode-Plus/files/12914852/crash-2023-10-16_20.47.06-client.txt)
https://mclo.gs/0FdiZUI

**Log**
[latest.log](https://github.com/YeoXuHang/Geode-Plus/files/12914840/latest.log)
https://mclo.gs/MxgXF2Y

**Comment by bons66** [comment]
Same versions - same problem. Geode+ 1.2.0 - work fine

**Comment by oguh43** [comment]
This line is crashing: https://github.com/YeoXuHang/Geode-Plus/blob/84d0722391b9b201a59fc35bc39c2c4eacd5eb50/common/src/main/java/net/yeoxuhang/geodeplus/mixin/BlockEntityWithoutLevelRendererMixin.java#L36C3-L36C3
The mixin name is invalid
