### ISSUE TITLE
[1.20.1] Incompatibility with Spelunkery

### ISSUE THREAD

**Issue by Reshy** [YeoXuHang/Geode-Plus#62]
Geode + is incompatible with spelunkery-1.20.1-0.3.4-forge.jar and it's rough gems.  Although in the minecraft game they share the same ID, they're not the same item for the purpose of the geode bud drops.  It would be nice if compatibility was added.

**Comment by YeoXuHang** [comment]
Im not sure what you mean by this tho? what gems

**Comment by Reshy** [comment]
The gems generated by the geodes, the diamond/emerald/etc. buds.  They aren't dropping anything when Spelunkery's installed.

**Comment by YeoXuHang** [comment]
Hmm that's weird

**Comment by YeoXuHang** [comment]
You mean fully grow clusters or

**Comment by Reshy** [comment]
Yes, fully grown bulb clusters, the large ones, won't drop their related items when Spelunkery is installed.

**Comment by YeoXuHang** [comment]
I don't see any code in spelunkery changing the loot table

**Comment by YeoXuHang** [comment]
There is no problem between spelunkery, I tested the clusters will drops items

**Comment by YeoXuHang** [comment]
Maybe youve installed other mod that disable the drop?
