### ISSUE TITLE
[1.20.1] Incompatibility with Alex's Caves Abyssal Chasm

### ISSUE THREAD

**Issue by Reshy** [YeoXuHang/Geode-Plus#63]
![image](https://github.com/YeoXuHang/Geode-Plus/assets/2096384/18b99667-543d-4096-90b7-6ac95bace600)

Geodes should probably either be blacklisted for the alexscaves:abyssal_chasm biome or at least check that they're not spawning in pure water.

**Comment by YeoXuHang** [comment]
Thx for telling me

**Comment by YeoXuHang** [comment]
this should be fixed
