### ISSUE TITLE
Idk what is causing this to crash

### ISSUE THREAD

**Issue by Marzky819** [YeoXuHang/Geode-Plus#64]
https://pastebin.com/igXKka8K
![Screenshot 2023-11-17 074544](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/882ad54a-e090-4073-a394-08db28af8151)

Here Is My Mods
![Screenshot 2023-11-17 074633](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/7d5d9c94-4ff5-4047-8ab9-111d381c1f02)
![Screenshot 2023-11-17 074646](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/69756740-5fc5-4e27-97e0-4f1301deddab)
![Screenshot 2023-11-17 074655](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/6a117f6e-3001-4706-9260-90f908a1a246)
![Screenshot 2023-11-17 074718](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/c7831ed5-6fd7-4d02-9304-894886fd6553)
![Screenshot 2023-11-17 074726](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/20019fbd-6b50-4fee-b724-79e5e32f3682)
![Screenshot 2023-11-17 074737](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/79ef486f-fe71-4e99-8d85-07563a0727ce)

![Screenshot 2023-11-17 074748](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/617a604b-f877-4983-ae3b-69af778ed117)
a3a70bc470)
![Screenshot 2023-11-17 074812](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/5fb1dc69-b13d-40b0-922d-e4ad7402aca9)
![Screenshot 2023-11-17 074836](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/58aed691-b468-4879-a7b8-ba19f6e6102d)
![Screenshot 2023-11-17 074846](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/e7137d18-cfe3-486e-b9e7-e77ec2d64451)

![Screenshot 2023-11-17 074857](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/31546635-fe2e-4611-8335-5a64a1c81ef7)
![Screenshot 2023-11-17 074902](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/cfadd9aa-f8b9-459c-8d5c-8e7539537748)

**Comment by YeoXuHang** [comment]
What version are you using forge

**Comment by YeoXuHang** [comment]
Also there is new update

**Comment by YeoXuHang** [comment]
Seems like some mod is not compatible with Geode+

**Comment by Marzky819** [comment]
![Screenshot 2023-11-17 075741](https://github.com/YeoXuHang/Geode-Plus/assets/151167593/99d0d2b9-6155-4d97-a1b7-7d754e2bd308)

new crash log https://pastebin.com/cWNiQdtj

**Comment by YeoXuHang** [comment]
It whether you disable Geode+ mod, or other mod. This crash is not caused by Geode+ itself

**Comment by Marzky819** [comment]
i know that it isn't geode plus that is causing it

**Comment by YeoXuHang** [comment]
Will list incompatible mods on Cf and Modrinth soon

**Comment by Marzky819** [comment]
that would be useful tbh
