### ISSUE TITLE
[Bug/Issue] Silk Touch doesn't work on budding ore blocks anymore?

### ISSUE THREAD

**Issue by SamHammie** [YeoXuHang/Geode-Plus#66]
Not sure if the initial ability to use silk touch may have been the bug, but it existed across several mod and Minecraft versions, so I wanted to make an issue in the hopes that the removal was unintentional.

Version 1.2.4 for 1.20.1 no longer allows you to silk touch budding blocks to get them. I get that budding amethyst and other modded buds normally disallow that, but it's such a useful feature to be able to move the blocks around that being unable to now has essentially ruined the economy of my server, and I've had to warn players not to break the budding ores anymore, even with silk touch, until I can potentially figure out the issue. If this doesn't get fixed, then we'll have to change server mods to something else that allows renewable ores.

**Comment by YeoXuHang** [comment]
You can enable it by going to config geode_plus.json5

**Comment by SamHammie** [comment]
@YeoXuHang The config option IS enabled. Also, I found out by mistake that it's happening for Budding Deepslate Lapis. I am not currently able to test other ores, but I can confirm at the very least that Budding Nether Glowstone, Quartz, and Gold Nugget still work fine.

**Comment by YeoXuHang** [comment]
I'll check out lapis, thx for informing

**Comment by FoggyWizard** [comment]
Happening with redstone too. Might want to take a look at all just to make sure.
