### ISSUE TITLE
Tons of Geodes generating in ocean biomes

### ISSUE THREAD

**Issue by MarcusTheAlbinoWolf** [YeoXuHang/Geode-Plus#67]
So I updated the mod and now a bunch of geodes are generating in ocean biomes, it's taking up too much space and I don't know how to fix it.

**Comment by YeoXuHang** [comment]
Increase the rarity in the config

**Comment by MarcusTheAlbinoWolf** [comment]
> Increase the rarity in the config
It the number supposed to go up or down?

**Comment by YeoXuHang** [comment]
I already said increase, so go up
