### ISSUE TITLE
[Bug] Sculk Columns generate outside of the Deep Dark and on the surface

### ISSUE THREAD

**Issue by DarthCaesium** [YeoXuHang/Geode-Plus#8]
As the title says, the curved sculk column thingies (idk the name) generate outside of the Deep Dark biome and on the surface when they shouldn't. Just in case, culprits could be Terrablender or Canary, but I previously had this issue with Deepslate Geodes spawning on the surface as well, and that got patched out, so I'm thinking it's an oversight on your end.

**Comment by YeoXuHang** [comment]
Fixed
